const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const content=$('#content'),preview=$('#preview'),message=$('#message'),status=$('#status');
const state={style:'rounded',eye:'soft',fg:'#151515',bg:'#ffffff',gradient:false,transparent:false,ga:'#151515',gb:'#725cff',logo:null,logoShape:'square',logoSize:22,qr:null,svg:''};
let timer=0;

function hexInput(id,key,out){$(id).addEventListener('input',e=>{state[key]=e.target.value;$(out).textContent=e.target.value.toUpperCase();render()})}
hexInput('#fg','fg','#fgHex');hexInput('#bg','bg','#bgHex');
$$('.style-btn').forEach(b=>b.addEventListener('click',()=>{state.style=b.dataset.style;$$('.style-btn').forEach(x=>x.classList.toggle('active',x===b));render()}));
$$('.seg').forEach(b=>b.addEventListener('click',()=>{state.logoShape=b.dataset.logoShape;$$('.seg').forEach(x=>x.classList.toggle('active',x===b));render()}));
$('#eyeStyle').addEventListener('change',e=>{state.eye=e.target.value;render()});
$('#gradient').addEventListener('change',e=>{state.gradient=e.target.checked;$('#gradientColors').classList.toggle('disabled',!state.gradient);render()});
$('#transparent').addEventListener('change',e=>{state.transparent=e.target.checked;render()});
$('#ga').addEventListener('input',e=>{state.ga=e.target.value;render()});$('#gb').addEventListener('input',e=>{state.gb=e.target.value;render()});
content.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(render,90)});
$('#logoSize').addEventListener('input',e=>{state.logoSize=+e.target.value;$('#logoSizeOut').textContent=`${state.logoSize}%`;render()});

const drop=$('#logoDrop'),file=$('#logoFile');
$('#chooseLogo').addEventListener('click',e=>{e.stopPropagation();file.click()});drop.addEventListener('click',e=>{if(e.target.id!=='chooseLogo')file.click()});
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));
drop.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)loadLogo(f)});file.addEventListener('change',e=>{const f=e.target.files[0];if(f)loadLogo(f)});
$('#removeLogo').addEventListener('click',()=>{state.logo=null;file.value='';$('#logoControls').classList.add('disabled');$('#uploadTitle').textContent='Add your logo';$('#uploadHint').textContent='PNG, JPG, WEBP or SVG · stays in your browser';render()});

function loadLogo(f){if(!/^image\/(png|jpeg|webp|svg\+xml)$/.test(f.type)){message.textContent='Please choose a PNG, JPG, WEBP or SVG logo.';return}if(f.size>6*1024*1024){message.textContent='That logo is larger than 6 MB. Please choose a smaller file.';return}const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1200,scale=Math.min(1,max/img.naturalWidth,max/img.naturalHeight),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(img,0,0,w,h);state.logo=c.toDataURL('image/png');$('#logoControls').classList.remove('disabled');$('#uploadTitle').textContent=f.name;$('#uploadHint').textContent='Loaded locally · ready to style';render()};img.onerror=()=>{message.textContent='That logo could not be read. Try a PNG or JPG.'};img.src=r.result};r.readAsDataURL(f)}

function modulePath(style,x,y,s){const cx=x+s/2,cy=y+s/2;if(style==='circle')return `<circle cx="${cx.toFixed(3)}" cy="${cy.toFixed(3)}" r="${(s*.42).toFixed(3)}"/>`;if(style==='diamond')return `<path d="M ${cx.toFixed(3)} ${y.toFixed(3)} L ${(x+s).toFixed(3)} ${cy.toFixed(3)} L ${cx.toFixed(3)} ${(y+s).toFixed(3)} L ${x.toFixed(3)} ${cy.toFixed(3)} Z"/>`;const r=style==='rounded'?s*.28:0;return `<rect x="${(x+s*.06).toFixed(3)}" y="${(y+s*.06).toFixed(3)}" width="${(s*.88).toFixed(3)}" height="${(s*.88).toFixed(3)}" rx="${r.toFixed(3)}"/>`}
function eyeShape(x,y,s,style,fill,bg){if(style==='circle'){return `<circle cx="${x+3.5*s}" cy="${y+3.5*s}" r="3.5" fill="${fill}"/><circle cx="${x+3.5*s}" cy="${y+3.5*s}" r="2.05" fill="${bg}"/><circle cx="${x+3.5*s}" cy="${y+3.5*s}" r="1" fill="${fill}"/>`}
const r=style==='soft'?'.75':'.15';return `<rect x="${x}" y="${y}" width="${7*s}" height="${7*s}" rx="${r*s}" fill="${fill}"/><rect x="${x+s}" y="${y+s}" width="${5*s}" height="${5*s}" rx="${r*s*.7}" fill="${bg}"/><rect x="${x+2*s}" y="${y+2*s}" width="${3*s}" height="${3*s}" rx="${r*s*.5}" fill="${fill}"/>`}
function buildSvg(qr){const n=qr.n,qz=4,total=n+qz*2,fg=state.gradient?'url(#g)':state.fg,bg=state.bg;let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" role="img" aria-label="Branded QR code">`;if(state.gradient)s+=`<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${state.ga}"/><stop offset="1" stop-color="${state.gb}"/></linearGradient></defs>`;if(!state.transparent)s+=`<rect width="${total}" height="${total}" fill="${bg}"/>`;s+=`<g fill="${fg}">`;
for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(qr.m[y][x] && !qr.fn[y][x])s+=modulePath(state.style,qz+x,qz+y,1);
s+='</g>';
s+=`<g>`+eyeShape(qz,qz,1,state.eye,fg,bg)+eyeShape(qz+n-7,qz,1,state.eye,fg,bg)+eyeShape(qz,qz+n-7,1,state.eye,fg,bg)+`</g>`;
// Preserve protected QR areas (timing, alignment, format/version) exactly as encoded.
s+=`<g fill="${fg}">`;for(let y=0;y<n;y++)for(let x=0;x<n;x++){if(!qr.fn[y][x]||!qr.m[y][x])continue;if((x<8&&y<8)||(x>=n-8&&y<8)||(x<8&&y>=n-8))continue;s+=`<rect x="${qz+x+.08}" y="${qz+y+.08}" width=".84" height=".84" rx=".1"/>`}s+='</g>';
if(state.logo){const center=total/2,size=total*(state.logoSize/100),pad=size*.13,outer=size+pad*2;const x=center-outer/2,y=center-outer/2,r=state.logoShape==='circle'?outer/2:outer*.18;s+=`<g><rect x="${x.toFixed(3)}" y="${y.toFixed(3)}" width="${outer.toFixed(3)}" height="${outer.toFixed(3)}" rx="${r.toFixed(3)}" fill="${bg}"/>`;const ir=state.logoShape==='circle'?size/2:size*.14;s+=`<image href="${state.logo}" x="${(center-size/2).toFixed(3)}" y="${(center-size/2).toFixed(3)}" width="${size.toFixed(3)}" height="${size.toFixed(3)}" preserveAspectRatio="xMidYMid meet" clip-path="url(#logoClip)"/>`;s+=`<defs><clipPath id="logoClip"><rect x="${(center-size/2).toFixed(3)}" y="${(center-size/2).toFixed(3)}" width="${size.toFixed(3)}" height="${size.toFixed(3)}" rx="${ir.toFixed(3)}"/></clipPath></defs></g>`}
s+='</svg>';return s}

function contrastRatio(a,b){const lum=h=>{const c=h.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(v=>v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4));return .2126*c[0]+.7152*c[1]+.0722*c[2]};const A=lum(a),B=lum(b);return (Math.max(A,B)+.05)/(Math.min(A,B)+.05)}
async function validate(svg,text){if(!('BarcodeDetector' in window))return null;try{const d=new BarcodeDetector({formats:['qr_code']}),img=new Image(),u=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});const c=document.createElement('canvas');c.width=c.height=1400;const x=c.getContext('2d');if(!state.transparent){x.fillStyle=state.bg;x.fillRect(0,0,1400,1400)}x.drawImage(img,0,0,1400,1400);URL.revokeObjectURL(u);const hits=await d.detect(c);return hits.some(h=>h.rawValue===text)}catch{return null}}
async function render(){message.textContent='';const value=content.value;$('#charCount').textContent=`${new TextEncoder().encode(value).length} bytes`;if(!value.trim()){preview.innerHTML='<div class="empty">Enter a URL or text to begin.</div>';status.className='status warn';status.textContent='⚠ Empty input';return}try{const qr=CreativeQR.encode(value,3);state.qr=qr;state.svg=buildSvg(qr);preview.innerHTML=state.svg;$('#versionInfo').textContent=`V${qr.version} · H error correction`;if(!state.gradient&&contrastRatio(state.fg,state.bg)<4.5){status.className='status warn';status.textContent='⚠ Low contrast'}else{const v=await validate(state.svg,value);if(v===true){status.className='status good';status.textContent='✓ Scan-ready'}else if(v===false&&state.logoSize>24){status.className='status warn';status.textContent='⚠ Logo is large — reduce it'}else{status.className='status good';status.textContent='✓ Designed for scanning'}}}catch(e){state.qr=null;state.svg='';preview.innerHTML='<div class="empty">This content is too long for a QR code.</div>';status.className='status bad';status.textContent='⚠ Content too long';message.textContent=e.message}}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),700)}
$('#svg').addEventListener('click',()=>{if(state.svg)download(new Blob([state.svg],{type:'image/svg+xml;charset=utf-8'}),`creative-qr-branded.svg`)});
$('#png').addEventListener('click',()=>{if(!state.svg)return;const img=new Image(),u=URL.createObjectURL(new Blob([state.svg],{type:'image/svg+xml'}));img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=2400;const x=c.getContext('2d');if(!state.transparent){x.fillStyle=state.bg;x.fillRect(0,0,2400,2400)}x.drawImage(img,0,0,2400,2400);c.toBlob(b=>{if(b)download(b,'creative-qr-branded.png');else message.textContent='PNG export failed.';URL.revokeObjectURL(u)},'image/png')};img.onerror=()=>{URL.revokeObjectURL(u);message.textContent='PNG export failed in this browser.'};img.src=u});
$('#logoSizeOut').textContent='22%';render();
